### ISSUE TITLE
命名規則を設ける

### ISSUE THREAD

**Issue by nobutilus** [renasami/myjlab_summer_2021_teamM#62]
概要: 各モジュール？ごとに命名規則を設ける

抱えている問題: 変数名がむちゃくちゃすぎてもうなにがなんだかわからなくなってしまっている・・・

備考: 参考になるサイトとかあればURLください

**Comment by renasami** [comment]
命名規則は基本的に言語のスタンダートに準拠でいいのでは
例外的なものは都度相談で

**Comment by nobutilus** [comment]
@renasami そうしよう

**Comment by nobutilus** [comment]
バックエンド側の命名規則は以下のURL通り

https://qiita.com/naomi7325/items/4eb1d2a40277361e898b
