### ISSUE TITLE
sqlalchemyから返ってくるデータを配列のように扱いたい。

### ISSUE THREAD

**Issue by nobutilus** [renasami/myjlab_summer_2021_teamM#64]
説明: 返ってくるデータの型がpython型ではなく、sql型とよばれる別のもので返ってきているようなので配列で返すようにしたい

解決したい問題: 配列のようにデータを扱えないため、データの加工に払う労力と時間がかかりすぎている。

備考: 参考になりそうなサイトのURL

https://qiita.com/hayashi-ay/items/4dc431003e7866d2aff8

https://kouki.hatenadiary.com/entry/2014/05/12/125333

**Comment by nobutilus** [comment]
蓮くんが教えてくれたようにレコードを一件ずつ抽出して辞書型に変換するやり方しかのってない。
上記URLのようにmodelsのclassにtoDict関数をつくって必要な場面で必要なデータに対して行えばある程度はやりやすくなる。

返すデータがjson形式だからいい別にいいってことなの?

**Comment by renasami** [comment]
jsonだからdictで返しておk！直接listで取ること意識しすぎて外部ライブラリ入れるよりcrud処理は簡潔にして取ってきたものを辞書化とかリスト化する関数作ればそれで解決するし

**Comment by nobutilus** [comment]
上記URLにて紹介されていた辞書化関数をすべてのテーブルファイルに追記したのでcloseします
