### ISSUE TITLE
API作る方法の確認

### ISSUE THREAD

**Issue by nobutilus** [renasami/myjlab_summer_2021_teamM#67]
説明: 今の作り方で本当にあっているのか？バックのテスト画面でも必要なパラメータにform{}とpost{}で二つでてきている。正しくない気がする。

解決したい問題: バックのテストではapiがつくれてるっぽい？が実際フロントでたたくと、うまく処理されていない。フロントでちゃんと動くようにしたい。

備考: バックエンドコンテナを起動後、http://localhost:8000/docs　のPOSTのAPIである/up/をみると、変なパラメータになっているのがわかる。

**Comment by renasami** [comment]
Apiテストページの併用で解決する気はする

**Comment by renasami** [comment]
作ったやつ

**Comment by nobutilus** [comment]
そうね、バックの人でも簡単に試せるように蓮くんがつくってくれたフロントのテストページ利用するやり方がいいと思う。

**Comment by nobutilus** [comment]
蓮くんがいいテストページつくってくれたので閉じます
