### ISSUE TITLE
__pycache__などの不要なファイルが.gitignoreできない

### ISSUE THREAD

**Issue by nobutilus** [renasami/myjlab_summer_2021_teamM#69]
説明: .gitignoreしているはずのファイルがgithubにあがってしまう

解決したい問題: そのせいでbranchから動けなくなってしまうことがある。
コンテナを作り直したり、プロジェクトフォルダを作り直す必要が出てきてしまって、もはや破壊である。

備考: 解決法がわからないのでいい方法があれば教えてください
ちなみにほかのグループでも同様の問題を抱えてたみたいです。
でもブランチによってはちゃんとignoreされてる時もあるんだよな・・・

**Comment by renasami** [comment]
文字コードの問題だったっぽいから一旦gitignore書き直してみた。多分これで大丈夫なはず

**Comment by nobutilus** [comment]
蓮くんがgitignore直してくれたのでclose
